notifiers:
  - email
safe_mode: true # doesn't delete the old key, only inactive it. Note: you will need to manually remove the inactive key before next run
aws_iam_users:
  - username: username2
    days: 60
    targets:
      - aws_secrets_manager_json:
          secret_arn: arn:aws:secretsmanager:eu-west-1:123456789:secret:test-12345
          access_key_id_property: AWS_SECRET_KEY_ID
          secret_access_key_property: AWS_SECRET_ACCESS_KEY
          kms_key_id: # (Optional) Specifies an updated ARN or alias of the AWS KMS customer master key
      - circleci_project:
          project_slug: github/user/project
          access_key_id_var_name: AWS_SECRET_KEY_ID
          secret_access_key_var_name: AWS_SECRET_ACCESS_KEY
      - circleci_context:
          context_id: 8cea5754-907d-4425-9b7f-8493de1efbfa
          access_key_id_var_name: AWS_SECRET_KEY_ID
          secret_access_key_var_name: AWS_SECRET_ACCESS_KEY
